services:
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    command:
      - start-dev
      - --import-realm
    volumes:
      - ./keycloak/priceflow-realm.json:/opt/keycloak/data/import/spring-realm.json
      - ./keycloak/HealthCheck.java:/opt/HealthCheck.java:ro
    healthcheck:
      test: ["CMD", "java", "/opt/HealthCheck.java", "http://localhost:9000/health/live", "||", "exit", "1"]
      interval: 5s
      timeout: 5s
      retries: 5
  consul:
    image: hashicorp/consul:1.19
    container_name: consul
    ports:
      - 8500:8500
      - 8600:8600/udp
    healthcheck:
      test: curl http://localhost:8500/v1/health/service/consul
  rabbitmq:
    container_name: "rabbitmq"
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 3
  prometheus:
    image: prom/prometheus
    container_name: prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - 9090:9090
    restart: unless-stopped
    volumes:
      - ./prometheus:/etc/prometheus
      - prom_data:/prometheus
    healthcheck:
      test: ["CMD", "wget", "--no-cache", "--spider", "http://localhost:9090/-/healthy"]
      interval: 5s
      retries: 3
  grafana:
    image: grafana/grafana
    container_name: grafana
    ports:
      - 3000:3000
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=grafana
    volumes:
      - ./grafana:/etc/grafana/provisioning/datasources
    healthcheck:
      test: curl http://localhost:3000/api/health
      interval: 5s
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - 3100:3100
    depends_on:
      - grafana
    healthcheck:
      test: ["CMD", "wget", "--no-cache", "--spider", "http://localhost:3100/ready"]
      interval: 5s
volumes:
  prom_data: