spring:
  management:
    endpoint:
      health:
        enabled: true
  security:
    oauth2:
      resourceserver:
        jwt:
          jws-algorithms: RS256 #default
          issuer-uri: http://keycloak:8080/realms/priceflow
server:
  port: 0
