spring:
  jpa:
    properties:
      hibernate:
        hbm2ddl:
          auto: update
          import_files_sql_extractor: org.hibernate.tool.schema.internal.script.MultiLineSqlScriptExtractor
  datasource:
    url: jdbc:h2:file:./db/offers;AUTO_SERVER=TRUE