services:
  rabbitmq:
    container_name: "rabbitmq"
    image: "rabbitmq:3-management"
    ports:
      - "5672:5672"
      - "15672:15672"
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 5s
      timeout: 5s
      retries: 3
  consul:
    image: hashicorp/consul:1.19
    container_name: consul
    ports:
      - "8500:8500"
      - "8600:8600/udp"
  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0
    ports:
      - 8080:8080
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_HEALTH_ENABLED=true
      - KC_METRICS_ENABLED=true
    command:
      - start-dev
      - --import-realm
    volumes:
      - ../keycloak/priceflow-realm.json:/opt/keycloak/data/import/spring-realm.json
      - ../keycloak/HealthCheck.java:/opt/HealthCheck.java:ro
    healthcheck:
      test: [ "CMD", "java", "/opt/HealthCheck.java", "http://localhost:9000/health/live", "||", "exit", "1" ]
      interval: 5s
      timeout: 5s
      retries: 5