insert into
    product (id, name, description)
values
    (1, 'Product A', 'Description for Product A'),
    (2, 'Product B', 'Description for Product B'),
    (3, 'Product C', 'Description for Product C'),
    (4, 'Product D', 'Description for Product D'),
    (5, 'Product E', 'Description for Product E'),
    (6, 'Product F', 'Description for Product F'),
    (7, 'Product G', 'Description for Product G'),
    (8, 'Product H', 'Description for Product H'),
    (9, 'Product I', 'Description for Product I'),
    (10, 'Product J', 'Description for Product J'),
    (11, 'Product K', 'Description for Product K'),
    (12, 'Product L', 'Description for Product L'),
    (13, 'Product M', 'Description for Product M'),
    (14, 'Product N', 'Description for Product N'),
    (15, 'Product O', 'Description for Product O'),
    (16, 'Product P', 'Description for Product P'),
    (17, 'Product Q', 'Description for Product Q'),
    (18, 'Product R', 'Description for Product R'),
    (19, 'Product S', 'Description for Product S'),
    (20, 'Product T', 'Description for Product T'),
    (21, 'Product U', 'Description for Product U'),
    (22, 'Product V', 'Description for Product V'),
    (23, 'Product W', 'Description for Product W'),
    (24, 'Product X', 'Description for Product X'),
    (25, 'Product Y', 'Description for Product Y'),
    (26, 'Product Z', 'Description for Product Z'),
    (27, 'Product AA', 'Description for Product AA'),
    (28, 'Product AB', 'Description for Product AB'),
    (29, 'Product AC', 'Description for Product AC'),
    (30, 'Product AD', 'Description for Product AD');