spring:
  application:
    name: priceflow-frontend
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: kc-provider
            clientId: frontend-app
            clientSecret: ${KC_CLIENT_SECRET}
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "http://localhost:8081/login/oauth2/code/{registrationId}"
            scope:
              - "openid"
        provider:
          kc-provider:
            issuer-uri: http://keycloak:8080/realms/priceflow
            user-name-attribute: email
  cloud:
    consul:
      host: consul
    openfeign:
      client:
        config:
          default:
            dismiss404: true
      http2client:
        enabled: true
  config:
    import: optional:file:.env[.properties]
  profiles:
    default: dev
server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: health, metrics, prometheus
  metrics:
    tags:
      application: ${spring.application.name}