spring:
  application:
    name: priceflow-frontend
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: kc-provider
            clientId: frontend-app
            clientSecret: hzRoxXRoyT3J6jwgOsq3rYjiAlFHCXXP
            authorization-grant-type: authorization_code
            client-authentication-method: client_secret_basic
            redirect-uri: "http://localhost:8083/login/oauth2/code/{registrationId}"
            scope:
              - "openid"
        provider:
          kc-provider:
            issuer-uri: http://keycloak:8080/realms/priceflow
            user-name-attribute: email
  thymeleaf:
    cache: false
server:
  port: 8083
logging:
  level:
    com:
      ludigi:
        priceflow:
          frontend:
            products: DEBUG

